### ISSUE TITLE
Merge relax-rest-client-dep into master

### ISSUE THREAD

**Issue by eliotjordan** [sul-dlss/rgeoserver#7]
It looks like the current version of the gem on Rubygems (0.7.10) was cut from a branch that never made it into master: [relax-rest-client-dep](https://github.com/sul-dlss/rgeoserver/blob/7fb034912c7c6b16cfa9261d737a05fa04324579/VERSION). The branch should be merged.

**Comment by drh-stanford** [comment]
I think that branch is stale as I never created a pull request for it. I've created a v0.7.10 release now.

**Comment by eliotjordan** [comment]
The geoserver documental now reflects the current gem repo:
http://docs.geoserver.org/latest/en/user/rest/examples/ruby.html

- E
